FROM apache/airflow:2.10.2

COPY requirements-airflow.txt /requirements-airflow.txt

RUN pip install --no-cache-dir -r /requirements-airflow.txt

WORKDIR /opt/airflow/project

ENV PYTHONPATH=/opt/airflow/project